# Generated by Django 5.2.8 on 2025-11-16 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('processing', 'กำลังดำเนินการ'), ('shipped', 'จัดส่งแล้ว'), ('delivered', 'ได้รับสินค้าแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ยอดรวม')),
                ('shipping_name', models.CharField(max_length=100, verbose_name='ชื่อผู้รับ')),
                ('shipping_address', models.TextField(verbose_name='ที่อยู่จัดส่ง')),
                ('shipping_phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สั่งซื้อ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งซื้อ')),
            ],
            options={
                'verbose_name': 'คำสั่งซื้อ',
                'verbose_name_plural': 'คำสั่งซื้อ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาต่อหน่วย')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='คำสั่งซื้อ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='สินค้า')),
            ],
            options={
                'verbose_name': 'รายการสินค้าในคำสั่งซื้อ',
                'verbose_name_plural': 'รายการสินค้าในคำสั่งซื้อ',
            },
        ),
    ]
