# Generated by Django 5.2.8 on 2025-11-17 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order', 'คำสั่งซื้อ'), ('promotion', 'โปรโมชั่น'), ('system', 'ระบบ')], max_length=20, verbose_name='ประเภท')),
                ('title', models.CharField(max_length=200, verbose_name='หัวข้อ')),
                ('message', models.TextField(verbose_name='ข้อความ')),
                ('link', models.CharField(blank=True, max_length=200, verbose_name='ลิงก์')),
                ('is_read', models.BooleanField(default=False, verbose_name='อ่านแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้')),
            ],
            options={
                'verbose_name': 'การแจ้งเตือน',
                'verbose_name_plural': 'การแจ้งเตือน',
                'ordering': ['-created_at'],
            },
        ),
    ]
