# Generated by Django 5.2.8 on 2025-11-17 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อร้าน')),
                ('description', models.TextField(blank=True, verbose_name='คำอธิบาย')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='shops/', verbose_name='โลโก้ร้าน')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='shops/banners/', verbose_name='แบนเนอร์')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='เบอร์โทร')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='อีเมล')),
                ('address', models.TextField(blank=True, verbose_name='ที่อยู่')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('is_verified', models.BooleanField(default=False, verbose_name='ยืนยันแล้ว')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไข')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าของร้าน')),
            ],
            options={
                'verbose_name': 'ร้านค้า',
                'verbose_name_plural': 'ร้านค้า',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.shop', verbose_name='ร้านค้า'),
        ),
    ]
